### ISSUE TITLE
Permission denied while running init command

### ISSUE THREAD

**Issue by dionysus98** [nextjournal/garden-cli#4]
While running the ```garden init``` command:
- it initializes the git repo
- then fails with this err: 
  ```sh
  arboretum@ssh.application.garden: Permission denied (publickey).
  ```

Running this on **linux, debian**.

**Comment by leahneukirchen** [comment]
You need to be part of the closed beta to sign up as a developer for this to work.  Register at https://application.garden/signup to get an invite when we grow our beta user group.
