### ISSUE TITLE
`garden secrets add`: Consider prompting the user to restart their application

### ISSUE THREAD

**Issue by teodorlu** [nextjournal/garden-cli#8]
Hi!

I confused myself a bit yesterday. I added a secret to my application, but couldn't figure out why I didn't see it from a production REPL.

```shell
$ echo -n foooooo | garden secrets add FOO        
Type your secret and press Enter:
Secret added successfully. Note that users with access to this project will be able to access it.
```

```clojure
;; From a production REPL before any appliaction restarts:
(System/getenv "FOO")
;; => nil
```

---

Maybe `garden secrets add` could inform the user that they have to restart their application before the new secret is available to the app as an environment variable?

**Comment by Sohalt** [comment]
Thanks! I've added a message.
